## Name: Soma Korada
## Email: somakorada@gmail.com
## Batch: 5

# 2A Assignment

Consider a neural network with three layers:
1.   Input layer with two inputs neurons
2.   One hidden layer with two neurons
3.   Output layer with a single neuron


![alt text](http://hmkcode.github.io/images/ai/nn1.png)

Let initial weights be as following: w1 = 0.13, w2 = 0.22, w3 = 0.11, w4 = 0.09, w5 = 0.16 and w6 = 0.18

![alt text](https://github.com/SomaKorada07/EIP/blob/master/bp_weights.png?raw=true)


Consider dataset with two inputs and one output.

![alt text](http://hmkcode.github.io/images/ai/bp_dataset.png)


Our single sample is as following inputs=[2, 3] and output=[1]

![alt text](http://hmkcode.github.io/images/ai/bp_sample.png)


# Forward Pass
The inputs are multiplied with the new weights and the results are passed to the next layer.

![alt text](https://github.com/SomaKorada07/EIP/blob/master/bp_forward.png?raw=true)

# Calculating Error
We can check the performance of the network by calculating the error. In our case, prediction is not close to the actual output meaning there is huge error.

![alt text](https://github.com/SomaKorada07/EIP/blob/master/bp_error.png?raw=true)

# Reducing Error
We need to reduce the error, i.e. difference between the prediction and actual output. As actual output is constant, we need to reduce the prediction.

As input values are constant, we need to change the weights in order to change the prediction.

![alt text](http://hmkcode.github.io/images/ai/bp_prediction_elements.png)

# Backpropagation
Backpropagation uses Gradient Descent concept to change the weights. It calculates the gradient of the error with respect to the weights.

![alt text](http://hmkcode.github.io/images/ai/bp_update_formula.png)

For example, to update w6, we take the current w6 and subtract the partial derivative of error function with respect to w6. Optionally, we multiply the derivative of the error function by a selected number to make sure that the new updated weight is minimizing the error function; this number is called learning rate.

![alt text](http://hmkcode.github.io/images/ai/bp_w6_update.png)

The derivation of the error function is evaluated by applying the chain rule as following

![alt text](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w6.png)

Hence the following

![alt text](http://hmkcode.github.io/images/ai/bp_w6_update_closed_form.png)

![alt text](http://hmkcode.github.io/images/ai/bp_w5_update_closed_form.png)

When moving backward to update w1, w2, w3 and w4 existing between input and hidden layer, the partial derivative for the error function with respect to w1, for example, will be as following:

![alt text](http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w1.png)

In summary, the update formulas for all weights will be as following:

![alt text](http://hmkcode.github.io/images/ai/bp_update_all_weights.png)

We can rewrite the update formulas in matrices as following:

![alt text](http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png)

![alt text](http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png)


# Backward Pass
Using the above formulae, new weights can be calculated as

![alt text](https://github.com/SomaKorada07/EIP/blob/master/bp_new_weights.png?raw=true)

Now, using the new weights we will repeat the forward pass.

![alt text](https://github.com/SomaKorada07/EIP/blob/master/bp_forward_2.png?raw=true)

The new prediction 0.28 is a little bit closer to actual output than the previously predicted one 0.235. We can repeat the same process of backward and forward pass until error is close or equal to zero.


# 2B Assignment








In [0]:
#forward pass with weights w1=.13,w2=.22,w3=.11,w4=.09,w5=.16,w6=.18
import numpy as np
input_array=np.array([[2,3]])
weights = np.array([[0.13,.11],[.22,.09]])
hidden_activation=np.dot(input_array,weights)
second_weights=np.array([[0.16],[0.18]])
out=np.dot(hidden_activation,second_weights)

In [0]:
out

array([[0.2354]])

In [0]:
#Calculating the error
actual = 1
error=(1/2)*(out[0][0]-actual)**2

In [0]:
#Assuming the learning rate as 0.05, find the delta
learning_rate = 0.05
delta = out[0][0] - actual
factor = learning_rate * delta

In [0]:
#finding the better weights to further reduce the error 
new_second_weights = second_weights -(np.transpose(hidden_activation)*factor)
new_weights = weights - (np.dot(np.transpose(input_array)*factor,np.transpose(second_weights)))

In [0]:
new_second_weights

array([[0.1951716],
       [0.1987327]])

In [0]:
new_weights

array([[0.1422336, 0.1237628],
       [0.2383504, 0.1106442]])

In [0]:
#Performing forward pass with the new weights - finding new output
new_weight_hidden = np.dot(input_array,new_weights)
new_output = np.dot(new_weight_hidden,new_second_weights)

In [0]:
new_output

array([[0.3102349]])